title: Rui Fan (Ranger)

meta_description: My name is Sjaak van den Berg and I'm a developer working with Ruby and JavaScript.
description: My name is <span itemprop='author' itemscope itemtype='https://schema.org/Person'>Sjaak van den Berg</span> and I'm a developer working with Ruby and JavaScript. You can reach me on Twitter via <a href='https://twitter.com/svdb' alt='@svdb on Twitter' title='@svdb on Twitter'>@svdb</a>.
author: Sjaak van den Berg
email: mail@svdb.co
pubkey: 13DB CAA1 2633 81A7
twitter: svdb
language: en
timezone: Europe/Amsterdam



theme: jekyll-theme-minimal
exclude_generator: ['tag', 'category']