theme: jekyll-theme-minimal

github:
  is_project_page: false
  is_user_page: false

exclude_generator: ['tag', 'category']

title: MIAS Group



# description: <p style="text-align:left"><img src="images/rui_fan.png" height="135" width="135"><br></p> <p style="text-align:left"><b>Postdoc Fellow</b><br>UC San Diego<br>La Jolla, CA 92093<br>the United States<br><a href="mailto:rui.fan@ieee.org">rui.fan@ieee.org</a></p>          
# <br><br><br>    <p>     &#8226 <a href="#about">About  <br><br>    &#8226 <a href="#featured_publications">Featured Publications</a>   <br><br>     &#8226 <a href="#lectures">Lectures</a>   <br><br>       &#8226 <a href="#tutorials_seminars">Tutorials & Seminars</a>     <br><br>    &#8226 <a href="#awards">Awards</a>    <br><br>   &#8226 <a href="#services">Services</a>    <br><br>   &#8226 <a href="#news">News</a></p>


