title: Rui Fan (Ranger)

description: My name is <span itemprop='author' itemscope itemtype='https://schema.org/Person'>Sjaak van den Berg</span> and I'm a developer working with Ruby and JavaScript. You can reach me on Twitter via <a href='https://twitter.com/svdb' alt='@svdb on Twitter' title='@svdb on Twitter'>@svdb</a>.

Rui FAN (Ranger) was born in Inner Mongolia in 1993. He received his BSc degree in Control Science and Engineering from <a href='https://en.wikipedia.org/wiki/Harbin_Institute_of_Technology' = the Harbin Institute of Technology</a>







theme: jekyll-theme-minimal
exclude_generator: ['tag', 'category']