theme: jekyll-theme-minimal

github:
  is_project_page: false
  is_user_page: false

exclude_generator: ['tag', 'category']

title: Rui FAN (Ranger)

description: </b><br><div align="justify"> <img src="images/rui_fan_lr_sq.jpg" alt="profile" height="140" width="140"> </div> <br>   <p>&#8226 <a href="#featured_publications">Featured Publications</a></p><p>&#8226 <a href="#services">Services</a></p> <p>&#8226 <a href="#lectures_tutorials_seminars">Lectures, Tutorials & Seminars</a></p> <p>&#8226 <a href="#awards">Awards</a></p> </div> <br>
