theme: jekyll-theme-minimal

github:
  is_project_page: false
  is_user_page: false

exclude_generator: ['tag', 'category']

title: Rui FAN (Ranger)



description: <img src="images/rui_fan_lr_sq.jpg" alt="profile" height="120" width="120"><br>


