title: Rui Fan (Ranger)

description: Rui FAN (Ranger) was born in Inner Mongolia in 1993. He received his BSc degree in Control Science and Engineering from <a href="https://en.wikipedia.org/wiki/Harbin_Institute_of_Technology">the Harbin Institute of Technology</a>. 





theme: jekyll-theme-minimal
exclude_generator: ['tag', 'category']