theme: jekyll-theme-minimal

github:
  is_project_page: false
  is_user_page: false

exclude_generator: ['tag', 'category']

title: Rui FAN (Ranger)



description: <img src="images/rui_fan_lr_sq.jpg" alt="profile" height="120" width="120"><b><font size="+1">About</font></b><br><div align="justify">Rui's research interests include computer vision, image processing and maching/deep learning. </div> <br>  <div align="left">&#8226 <a href="https://scholar.google.com.hk/citations?user=P5AJTXcAAAAJ&hl=en">Google Scholar</a></div><br> <div align="left"> e-mail:<a href="mailto:rui.fan@ieee.org"> rui.fan@ieee.org</a></div>


