theme: jekyll-theme-minimal

github:
  is_project_page: false
  is_user_page: false

title: ruirangerfan.com

description: </div><br> <img src="images/rui_fan_lr_sq.jpg" alt="profile" height="100" width="100"> </div> <br>  <div align="left">&#8226 <a href="https://scholar.google.com.hk/citations?user=P5AJTXcAAAAJ&hl=en">Google Scholar</a></div><br> <div align="left"> e-mail:<a href="mailto:rui.fan@ieee.org"> rui.fan@ieee.org</a><br></div>
